{{- $secretName := include "kutt.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.kutt.auth.existingSecret }}
  JWT_SECRET: {{ .Values.kutt.auth.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.kutt.db.existingSecret) (not .Values.postgresql.enabled) (not .Values.mariadb.enabled) }}
  DB_PASSWORD: {{ .Values.kutt.db.password | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.kutt.redis.existingSecret) (not .Values.redis.enabled) }}
  REDIS_PASSWORD: {{ .Values.kutt.redis.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.kutt.mail.enabled (not .Values.kutt.mail.existingSecret) }}
  MAIL_PASSWORD: {{ .Values.kutt.mail.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.kutt.oidc.enabled (not .Values.kutt.oidc.existingSecret) }}
  OIDC_CLIENT_SECRET: {{ .Values.kutt.oidc.clientSecret | b64enc | quote }}
  {{- end }}
